name: ML_pymc4
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.17.0
  - ipykernel=6.29.2
  - ipython=8.22.1
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - numpy=1.25.2
  - pandas=2.2.1
  - pymc=5.10.4
  - pymc-base=5.10.4
  - python=3.11.8
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
